### ISSUE TITLE
gem not working at all

### ISSUE THREAD

**Issue by LukasBarry** [rubyhero/chartable#2]
I made a sample app to test this gem and see if it would work for a larger project. I added the gem to the gemfile, bundled, and created a `Survey` model with no attributes besides `created_at` and `updated_at`. I seeded the database with 50 surveys with random `created_at` attributes so it would have something to group.

When I run `Survey.analytics(:monthly)` in my console, I get the following errors:

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: DATE_FORMAT: SELECT COUNT(*) AS count_all, DATE_FORMAT(created_at,'%M %Y') AS date_format_created_at_m_y FROM "surveys" GROUP BY DATE_FORMAT(created_at,'%M %Y')
```

Nothing I have tried has successfully returned a grouped hash at all.

Any ideas?

I am using ruby version 2.3.4 and SQLite3 since no database type was specified.

**Comment by rubyhero** [comment]
@LukasBarry I should specify in the README which databases are supported, currently only MySQL and PostgreSQL. I will check if there is a replacement for the `DATE_FORMAT` function in the SQLite database

**Comment by LukasBarry** [comment]
I actually did try installing the gem in a project that is using postgres, and i had the exact same error, minus the specification on SQLite3. That project was using ruby 2.4.4. But it still returned the error `no such function: DATE_FORMAT`

**Comment by rubyhero** [comment]
@LukasBarry thank you for checking this. I found a way to make it work on SQLite so I will take care of the PostgreSQL support after this. I should run specs more carefully before pushing the current version

**Comment by rubyhero** [comment]
@LukasBarry I added support for the SQLite and PostgreSQL databases. Updates are already pushed, you can pull `0.0.0.2` version. Please let me know if it works for you now

**Comment by LukasBarry** [comment]
Works great!! Thanks!
