### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SonalBhanawat** [rubyhero/chartable#5]
tried using in version 2.0.0 giving some syntax errors

**Comment by rubyhero** [comment]
@SonalBhanawat can you past the error here?

**Comment by SonalBhanawat** [comment]
gems/chartable-0.0.0.2/lib/chartable/queries/daily.rb:8: syntax error, unexpected ')' (SyntaxError)

**Comment by rubyhero** [comment]
@SonalBhanawat what Ruby version do you use? How the query that produces this error looks like?

**Comment by SonalBhanawat** [comment]
ruby 2.0.0 version
Just bundled this and trying to open rails console on which this is throwing this error

**Comment by rubyhero** [comment]
@SonalBhanawat thank you, I will take look into it

**Comment by rubyhero** [comment]
@SonalBhanawat it fails because you are using ruby 2.0.0 and support for required keyword arguments was introduced in ruby 2.1. So to continue using gem you have to upgrade your Ruby version to 2.1
