### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::GroupingError: ERROR

### ISSUE THREAD

**Issue by polomasta** [rubyhero/chartable#6]
Hi there... enjoying trying out this gem, thank you!

I've run into this error: `ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "messages.created_at" must appear in the GROUP BY clause or be used in an aggregate function`

I'm essentially doing `Message.where(attribute: x).analytics(:monthly)`

I have virtually the same thing working just fine on another model ... not quite sure how to get around it... appreciate any insights!

**Comment by rubyhero** [comment]
@polomasta thank you for reporting this. I will take a look at it

**Comment by rubyhero** [comment]
@polomasta I'm not able to reproduce it. Can you paste the output of `Message.where(attribute: x).to_sql` ? It seems like you have some kind of default scope that specifies the column names but does not include the `created_at` attribute.

**Comment by rubyhero** [comment]
I'm closing this one due the lack of response
