### ISSUE TITLE
Order of results

### ISSUE THREAD

**Issue by bojates** [rubyhero/chartable#8]
Thank you for this gem. Am I missing something? When I pull back results, they are not being ordered by the created_date (or other grouping value passed in). e.g. a :monthly query without specifying a grouping field is returning the records in this order. 

{"April 2017"=>1, "November 2016"=>1, "August 2016"=>49, "September 2016"=>73, "February 2017"=>5}

Is there a way to specify the order?

Thanks.

**Comment by rubyhero** [comment]
@bojates I will look into this, thank you for submitting the issue!

**Comment by nmeynard** [comment]
Any update ?
Issue is still present in 0.0.0.2
{nil=>12, "April 2018"=>1, "August 2018"=>2, "July 2018"=>4, "June 2018"=>7, "May 2018"=>4, "November 2018"=>10, "October 2018"=>30, "September 2018"=>18}

**Comment by rubyhero** [comment]
@nmeynard Thank you for the reminder. I have some work in progress to fix this issue, I will finish it in the next few days

**Comment by nmeynard** [comment]
the issue comes from the results being returned in alphabetical order (and by year when two months begin with the same letter)

**Comment by rubyhero** [comment]
@bojates @nmeynard issue is finally fixed. You can can now specify results order by passing `order` option with `desc` or `asc`:

```ruby
User.analytics(:monthly, order: 'desc')
```

The new version is `0.0.0.3`
