### ISSUE TITLE
undefined method `analytics' 

### ISSUE THREAD

**Issue by AstmDesign** [rubyhero/chartable#9]
Hello Guys,
I installed the gems 
```
gem 'chartkick'
gem 'chartable'
```
in my Gemfile and `bundle install` & also `bundle update`
And in my controller  I added this code

`@users =User.analytics(:daily)
`
In my local laptop every thing going well, But when I deployed it to the server I found its giving me the below issue.

`NoMethodError (undefined method analytics for #<User::ActiveRecord_Relation:0x000000070f3708>):`

BTW, I checked the gems in my Gemfile and find them installed on the server.
How I can fix it?!

**Comment by rubyhero** [comment]
@AstmDesign Hello, can you post the code that is causing this error? You posted the case with the `User` model but you have an error for `Content`

**Comment by AstmDesign** [comment]
Hi @rubyhero, 
I copied the error from another page, I edited the post.

**Comment by rubyhero** [comment]
@AstmDesign Thank you. What Ruby and Rails version do you use?

**Comment by AstmDesign** [comment]
@rubyhero :
This is my server ruby version:  ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by rubyhero** [comment]
@AstmDesign can you add also your Rails version? It will help me to debug the issue

**Comment by AstmDesign** [comment]
@rubyhero , it's the  Rails 4.2.5.1, I found It the same version on my local laptop also.
Maybe this is not the issue because the Gem working well with me locally

**Comment by AstmDesign** [comment]
@rubyhero, This is all the versions on server  
**$gem -v**
`2.6.14`
**$bundle -v**
`Bundler version 1.16.3`
**$ruby -v**
`ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]`
**$rails -v**
`Rails 4.2.5.1`

**Comment by rubyhero** [comment]
@AstmDesign thank you, I will take a look at it during this weekend

**Comment by rubyhero** [comment]
@AstmDesign I tried to reproduce this issue with the same setup as you have but the only way to reproduce this on the development is to wrap the gem definition into `production` group in the `Gemfile`:

```ruby
group :production do
  gem 'chartable'
end
```

are you sure you didn't do the same but in the `development` group that's why it doesn't work in the production environment?

**Comment by AstmDesign** [comment]
HI @rubyhero,
This issue makes me crazy and decided to discover why the server doing something like that?!
so checked the server today & upgraded the ruby version and the gems and the bundle and unicorn, notes that the unicorn still using the old ruby version so restarted it again and deployed new version then found it working well.

Many thanks for you @rubyhero, Now I'm finally enjoying myself by using your amazing Gem.

Regards
